module.exports = {
    TwoZeroFourEight: require('./src/2048'),
    Connect4: require('./src/Connect4'),
    FastType: require('./src/FastType'),
    FindEmoji: require('./src/FindEmoji'),
    Fishy: require('./src/Fishy'),
    Flood: require('./src/Flood'),
    Hangman: require('./src/Hangman'),
    MatchPairs: require('./src/MatchPairs'),
    Minesweeper: require('./src/Minesweeper'),
    GuessThePokemon: require('./src/GuessThePokemon'),
    RockPaperScissors: require('./src/RockPaperScissors'),
    WouldYouRather: require('./src/WouldYouRather'),
    version: require('./package.json').version,
    TicTacToe: require('./src/TicTacToe'),
    Emojify: require('./utils/emojify'),
    Slots: require('./src/Slots'),
    Snake: require('./src/Snake'),
    Trivia: require('./src/Trivia'),
    Wordle: require('./src/Wordle'),
    GuessTheNumber: require('./src/GuessTheNumber')
}